platform :ios, '7.0'
def testing_pods
    pod 'AFNetworking', '~> 3.0’
    pod 'Masonry'
    pod 'MBProgressHUD', '~> 0.9.1'
    pod 'MJExtension', '~> 3.0.10'
end

target ‘SeaBattle’ do
    testing_pods
end
